### ISSUE TITLE
Si potrebbe passare a Bullseye? La versione di python su Buster è la 3.7

### ISSUE THREAD

**Issue by sergiocorato** [kenayagi/docker-odoo#17]
https://github.com/kenayagi/docker-odoo/blob/c460cc42af3c7907a3d073ddf50ab6d5cee27dc1/Dockerfile#LL1C15-L1C15

**Comment by kenayagi** [comment]
Personalmente non avrei obiezioni.

Ho usato Buster prendendo come riferimento l'immagine ufficiale per 14.0, che è su Buster e Python 3.7.3

https://github.com/odoo/docker/blob/42cc6f7d3a35dd7ab2353e09cfecf48c1bf50ee1/14.0/Dockerfile

Non vedo inoltre una versione specifica per bullseye di [wkhtmltopdf](https://github.com/odoo/odoo/wiki/Wkhtmltopdf)

https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.5

Suggerimenti?

**Comment by kenayagi** [comment]
Pare che usino la stessa versione anche su 16.0 (che è su bullseye).

https://github.com/odoo/docker/blob/42cc6f7d3a35dd7ab2353e09cfecf48c1bf50ee1/16.0/Dockerfile#L34

Dunque presumo sia ok.

Teniamo la versione Python di default su Bullseye o ne piazziamo una specifica? 😁

**Comment by sergiocorato** [comment]
Bene, beh ho in uso la 3.8.16 in locale, però i test su github viaggiano su
Ubuntu 22.04
https://github.com/sergiocorato/e-account/blob/80a3bca2e14f988df6ee21cb5638d1e489988f43/.github/workflows/pre-commit.yml#L14
, quindi si potrebbe prendere la versione di default installata là
Sergio Corato


Il giorno mer 7 giu 2023 alle ore 12:09 K ***@***.***> ha
scritto:

**Comment by kenayagi** [comment]
Attualmente [Ubuntu 22.04 è su Python 3.10.6](https://packages.ubuntu.com/jammy-updates/python3)

Creo una nuova immagine con Python da sorgenti.

(Ci sarebbe anche [questa](https://hub.docker.com/layers/library/python/3.10.6-bullseye/images/sha256-8d1f943ceaaf3b3ce05df5c0926e7958836b048b700176bf9c56d8f37ac13fca?context=explore), ma mi sembra un po' più sporca)

**Comment by sergiocorato** [comment]
Ok, dovrei passare a questo punto anche in locale alla stessa versione.

**Comment by kenayagi** [comment]
> Ok, dovrei passare a questo punto anche in locale alla stessa versione.

pyenv! 😜

**Comment by kenayagi** [comment]
[Nuova versione](https://github.com/kenayagi/docker-odoo/blob/d54874f060749927bc7679f4630e17b120ff75a1/Dockerfile) creata e pronta per i test.

**Comment by sergiocorato** [comment]
🎉😎
Sergio Corato


Il giorno mer 7 giu 2023 alle ore 15:53 K ***@***.***> ha
scritto:
