### ISSUE TITLE
Having issue with DockerFile

### ISSUE THREAD

**Issue by kathpalrk** [kenayagi/docker-odoo#3]
Step 40/48 : RUN pip install /opt/odoo
 ---> Running in edc79e7a7eb2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /opt/odoo
ERROR: Package 'odoo' requires a different Python: 2.7.13 not in '>=3.5'

**Comment by kenayagi** [comment]
I'm sorry, but I can't reproduce this issue.
Could you try again or provide further details?
